Updated the Codebase to use pathlib instead of using os.path and path.py
openzim/gutenberg pull request #208
Opened 2023-12-20 13:36 UTC by MUCCHU

Changed multiple files to make sure consistency is maintained by using pathlib to handle file operations. Thereby solving issue #195 . After the changes I ran the docker container which worked perfectly fine.

2023-12-21 08:51 UTC, benoit74 commented on src/gutenberg2zim/download.py
>              continue
Now that we have a great function to skip folders, let's use this (previous code was a bit ... risky)
```suggestion
        if not Path(zipped_file).is_file:
```

2023-12-21 08:58 UTC, benoit74 commented on src/gutenberg2zim/export.py
`file_path.unlink(missing_ok=True)` would be better than `try ... except`

2023-12-21 08:59 UTC, benoit74 commented on src/gutenberg2zim/export.py
>                  opff_content, _ = read_file(opff)
opff is already a Path
```suggestion
            if opff.exists():
```

2023-12-21 09:00 UTC, benoit74 commented on src/gutenberg2zim/export.py
>                  Global.add_item_for(path=dstfname, fpath=dst)
`dst` is already a Path

```suggestion
                tmp_epub.rename(dst / tmp_epub.name)
```

2023-12-21 09:06 UTC, benoit74 commented on src/gutenberg2zim/download.py
> +            fname = Path(zipped_file).name
`src` is already a Path
```suggestion
        if src.exists():
```

2023-12-21 09:06 UTC, benoit74 commented on src/gutenberg2zim/download.py
>              except Exception as e:
Idem
```suggestion
                src.rename(dst)
```

2023-12-21 09:11 UTC, benoit74 commented on src/gutenberg2zim/download.py
> +    book_dir = Path(download_cache).joinpath(str(book.id))
`download_cache` should be passed as a Path from the beginning, so that we stop building this Path object again and again for all books.

2023-12-21 09:22 UTC, benoit74 requested changes
Thank you, this is a very good first PR.

Which docker command did you ran? (it is pretty hard to run a full scrape and be sure that you exercise all code branches, at least it takes time)

I made some inline comments.

In addition to them, I would like:
- please choose between the `/ ` operator or the `joinpath` function to combine paths, for consistency. Here you use both, and I find it does not help to read the code. Except if there are any good reasons to sometime use one and sometime prefer the other, but this is not obvious for me
- please add an entry to the ChangeLog in the Unreleased section (you will probably need a new "Changed" subsection as well, there is none for now)

Some other remarks (this is not something to worry too much about, this is just our way of working):
- please always add the "Fix: #xxx" text in your first comment, so that the issue is automatically closed when PR is merged
- please assign a reviewer once PR is ready (when in doubt, ask who is the right person, but I'm the reviewer of all openZIM Python scrapers) ; this is the trigger for my action, no need to notify anywhere else
- PR is not ready if CI is failing ; if it is not clear for you why CI is failing, ask for help
  - this is more a general remark, because here it was hard to understand what was going on, there was a nasty issue in `main` branch, so I fixed it myself
- much more details on all this in https://github.com/openzim/overview/wiki/openZIM-workflow

2023-12-21 09:25 UTC, benoit74 commented
Nota: black formatting is not OK as well ; you should probably:
- create a virtual environment with all dev dependencies with `hatch shell` (if not already done)
- activate pre-commit (`pre-commit install` in base repo folder) to detect such issues at commit time
- you can fix most of these issues with `invoke fixall` (in base repo folder again)

2023-12-21 18:48 UTC, MUCCHU commented
Thank you for the feedback. I made all the changes you requested and also ensured that the formatting is perfect by enabling pre-commit. Kindly review the PR.

2023-12-21 19:59 UTC, benoit74 commented
I really like what you did, good job.
Just give me some time to start an end-to-end test and I will come back to you.

2023-12-27 07:52 UTC, benoit74 commented
Still did not had time to start a test run, sorry about that.

2024-01-09 10:38 UTC, benoit74 requested changes
Please ensure that a full run (e.g. `python src/gutenberg2zim`) passes before requesting again a review.

Ziming a single book does not work:

```
python src/gutenberg2zim --books 84
```

2024-01-26 13:49 UTC, benoit74 commented
Closed for inactivity, feel free to reopen if you have new changes to submit.

2024-01-26 13:49 UTC, closed without merging

2024-03-26 14:59 UTC, elfkuzco commented
I would like to finish this PR @benoit74