Replace usage of os.path and path.py with pathlib
openzim/gutenberg pull request #225
Opened 2024-04-13 11:06 UTC by elfkuzco

## Rationale

Use `pathlib.Path` for all path operations instead of a combination of `os.path` and `path.py`. This is intended as a fix for #195 

## Changes
- Replace all usages of `os.path` and `path.py` to `pathlib.Path`
- Add type annotations for some parts of the code
- Use f-strings to build urls instead of `os.path.join`

2024-04-15 08:43 UTC, benoit74 requested changes
Thank you, this looks very good, only minor comments to discuss (not sure I'm right on all of them ^^)

2024-04-15 08:43 UTC, benoit74 commented on src/gutenberg2zim/download.py
> +        if (book_dir / "optimized" / cover).exists() or (
This is hard to read, please add back the outermost parentheses if possible, so that code is written more clearly

2024-04-15 08:43 UTC, benoit74 commented on src/gutenberg2zim/entrypoint.py
> +                output_folder=output_folder,
We prefer to avoid assigning variables which are used only once, this proved to be confusing for next maintainers. 

You should rewrite this `output_folder = Path(one_lang_one_zim_folder).resolve() if one_lang_one_zim_folder else Path(".").resolve()`

2024-04-15 08:43 UTC, benoit74 commented on src/gutenberg2zim/export.py
> +    return (Path(gutenberg2zim.__file__).parent / "templates").resolve()
Do we really need to `resolve` here? `gutenberg2zim.__file__` is already resolved

2024-04-15 08:43 UTC, benoit74 commented on src/gutenberg2zim/download.py
> +        if not Path(zipped_file).resolve().is_file():
How can it work? `zipped_file` is path inside the ZIP, isn't it?

2024-04-15 08:43 UTC, benoit74 commented on src/gutenberg2zim/download.py
> +        src = (Path(tmpd) / zipped_file).resolve()
Do we really need to `resolve` here? `tmpd` is already resolved

2024-04-15 08:43 UTC, benoit74 commented on src/gutenberg2zim/rdf.py
> +        curd = Path(__file__).resolve().parent
Do we really need to `resolve` here? `__file__` is already resolved

2024-04-15 08:43 UTC, benoit74 commented on src/gutenberg2zim/urls.py
> +    book = Book.get(id=84)
Do we really need to change this? Book id 9 is wrong?

2024-04-16 14:56 UTC, elfkuzco commented on src/gutenberg2zim/download.py
> +        if (book_dir / "optimized" / cover).exists() or (
Okay

2024-04-16 14:56 UTC, elfkuzco commented on src/gutenberg2zim/entrypoint.py
> +                output_folder=output_folder,
Okay. Will do that

2024-04-16 14:56 UTC, elfkuzco commented on src/gutenberg2zim/export.py
> +    return (Path(gutenberg2zim.__file__).parent / "templates").resolve()
Yeah, you are right. That is absolutely redundant

2024-04-16 14:58 UTC, elfkuzco commented on src/gutenberg2zim/download.py
> +        if not Path(zipped_file).resolve().is_file():
According to the comment, it should skip folders, hence the `is_file()` call. For the call to `resolve()`, I was experimenting with the list of items returned from a zip file and they are all relative to the zipped file. However, looking at it now, I think it should work without the `resolve()` call

2024-04-16 15:02 UTC, elfkuzco commented on src/gutenberg2zim/download.py
> +        src = (Path(tmpd) / zipped_file).resolve()
While rewriting the code, I didn't know exactly which folders were passed as arguments and started resolving from the bottom up. But now that I know better, I certainly think I can do better by removing the redundant `resolve()` calls. Thanks for pointing that out.

2024-04-16 15:03 UTC, elfkuzco commented on src/gutenberg2zim/urls.py
> +    book = Book.get(id=84)
Oh, my bad. This is when I was testing the `urls.py` script after downloading book 84. Another oversight.

2024-04-19 13:42 UTC, elfkuzco commented on src/gutenberg2zim/download.py
> +        if (book_dir / "optimized" / cover).exists() or (
Tried to add the outermost parentheses but `black` keeps reformatting it.

2024-04-22 11:52 UTC, elfkuzco commented
@benoit74 , I have made the necessary fixes but I'm unable to run the full check anymore as my VM instance on GCP keeps running out of space (over 20Gb). However, I can verify that the previous commands run to full completion

2024-04-30 11:01 UTC, benoit74 commented
> I have made the necessary fixes but I'm unable to run the full check anymore as my VM instance on GCP keeps running out of space (over 20Gb). However, I can verify that the previous commands run to full completion

That's enough for me, we will make a full run before releasing this anyway.

2024-04-30 11:02 UTC, benoit74 approved these changes
LGTM

2024-04-30 11:03 UTC, merged